### PR TITLE
loopback static page for home and tutorial

### PR DESCRIPTION
**Pull request by siddhipai**
@ritch @crandmck PTAL

loopback_home.html
- There are some issues adjusting thumbnails dimensions with respect to width:419px.
- I need settings icon to be added in each thumbnail.

loopback_tutorial.html
- Vertical line passing through bullets in table of contents is not yet added.Weirdly facing issues in that.So trying that.
- I need wifi icon to be added page.

Please let me know if anything has to changed in existing design.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
In general, this looks good, but:
- Please use the existing `css` and `js` directories for stylesheets and JavaScript files, respectively, instead of creating your own new directories  under `proto`.  The `css` dir already has `bootstrap.min.css` but feel free to add any other files that you need.
- It [looks like you're using Grunt for something](https://github.com/ibm-apiconnect/getting-started/pull/2/files#diff-88576b223e86a1a19a9dcceac907b983). Is that true?  If so, please add some information on what one needs to do in the README, so we can easily build the site if you're not available.
- It would also be nice to _temporarily_ add links to your new pages `loopback_home.html` and `loopback_tutorial.html` in the main [index.md](https://github.com/ibm-apiconnect/getting-started/blob/gh-pages/index.md) file so they will be easy for Ritchie and Adam to find as we iterate on the design/implementation.

**Comment by siddhipai** [comment]
I am not using grunt. I think that one is an autogenerated file.

**Comment by crandmck** [comment]
LGTM, thanks!

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request merged**
